# http
POST http://localhost:3000/api/wilders/create HTTP/1.1
content-type: application/json

{
    "name":"Http Wilder",
    "city": "Londres",
    "skills":[
        {"title":"express", "votes":5},
        {"title":"mongo", "votes":12}
    ]
}

###

GET http://localhost:3000/api/wilders/all 

###

GET http://localhost:3000/api/wilders/city/Londres 

###

PUT http://localhost:3000/api/wilders/updateWilder/6227ad674e99deee8dbbdb12 
content-type: application/json

{
    "city": "Villeurbanne"
}

###

DELETE  http://localhost:3000/api/wilders/delete/6227ad674e99deee8dbbdb12

###

DELETE  http://localhost:3000/api/wilders/delete/
